/**
 * Itinerary assembler — converts agent proposals + consensus result into the
 * final structured Itinerary saved to the database.
 *
 * Output shape (stored as JSON columns in Itinerary model):
 *   dayPlans           — day-by-day plan with morning/afternoon/evening blocks
 *   budgetBreakdown    — per-category cost breakdown
 *   satisfactionScores — per-member (keyed to User.id) + group score
 *   tradeoffReport     — plain-language narrative (generated by Claude)
 */

import Anthropic from '@anthropic-ai/sdk';
import type {
  PlanningContext,
  ActivityProposal,
  FoodProposal,
  AccommodationProposal,
  TransportationProposal,
  BudgetProposal,
  ActivityCandidate,
  Meal,
} from './schemas';
import type { ConsensusResult } from './consensus';
import type { NegotiationResult } from './negotiation';
import type { MemberSatisfaction } from './scoring';

const anthropic = new Anthropic();

function model(): string {
  return process.env.CLAUDE_MODEL ?? 'claude-haiku-4-5-20251001';
}

function stripFences(raw: string): string {
  return raw.replace(/^```(?:json)?\s*/m, '').replace(/\s*```\s*$/m, '').trim();
}

// ---------------------------------------------------------------------------
// Output types (stored in DB as JSON)
// ---------------------------------------------------------------------------

export type TimeBlock = 'morning' | 'afternoon' | 'evening';

export interface ScheduledBlock {
  timeBlock:          TimeBlock;
  type:               'activity' | 'meal' | 'travel' | 'free';
  title:              string;
  venue:              string;
  location:           string;   // neighbourhood / area
  estimatedCostPerPersonUsd: number;
  travelTimeMinutes?: number;
  durationHours?:     number;
  /** Which member preferences (Must Have / Nice to Have) this block serves. */
  servesPreferences:  Record<string, string[]>;  // memberId → [pref labels]
  notes?:             string;
}

export interface DayPlan {
  day:      number;
  date?:    string;    // ISO date string if start date known
  theme:    string;    // short label e.g. "Culture & Food Day"
  blocks:   ScheduledBlock[];
  dayTotalCostPerPersonUsd: number;
}

export interface BudgetLine {
  category:                  string;
  estimatedCostPerPersonUsd: number;
  totalGroupUsd:             number;
  pctOfBudget:               number;
}

export interface BudgetBreakdown {
  lines:             BudgetLine[];
  totalPerPersonUsd: number;
  totalGroupUsd:     number;
  lockedBudgetUsd:   number;
  surplus:           number;
  notes:             string;
}

export interface PerMemberScore {
  memberId:          string;   // User.id — attributable to the Google-authenticated User
  memberRecordId:    string;   // Member.id for DB joins
  memberName:        string;
  satisfactionPct:   number;
  mustHaveFulfilled: string[];
  niceToHaveFulfilled: string[];
  unmetMustHave:     string[];
}

export interface SatisfactionScores {
  perMember:         PerMemberScore[];
  groupSatisfactionPct: number;
  fairnessScore:     number;
  fairnessFloorMet:  boolean;
}

export interface FinalItinerary {
  dayPlans:           DayPlan[];
  budgetBreakdown:    BudgetBreakdown;
  satisfactionScores: SatisfactionScores;
  tradeoffReport:     string;
  adminOverrideFlag:  boolean;
  negotiationRounds:  number;
  generatedAt:        string;   // ISO timestamp
}

// ---------------------------------------------------------------------------
// Day planner — slots activities and meals into morning/afternoon/evening
// ---------------------------------------------------------------------------

function slotActivitiesAndMeals(
  activities: ActivityCandidate[],
  meals: Meal[],
  tripDuration: number,
  members: PlanningContext['members'],
): DayPlan[] {
  const days: DayPlan[] = [];

  // Spread activities across days (round-robin, morning first then afternoon)
  const activityQueue = [...activities];

  for (let day = 1; day <= tripDuration; day++) {
    const blocks: ScheduledBlock[] = [];
    const dayMeals = meals.filter(m => m.day === day);

    // Morning: first activity of the day (or breakfast if none)
    const morningActivity = activityQueue.shift();

    const breakfast = dayMeals.find(m => m.type === 'breakfast');
    if (breakfast) {
      blocks.push(mealToBlock('morning', breakfast, members));
    } else if (morningActivity) {
      blocks.push(activityToBlock('morning', morningActivity, members));
    }

    // Afternoon: second activity or lunch
    const afternoonActivity = activityQueue.shift();
    const lunch = dayMeals.find(m => m.type === 'lunch');

    if (lunch) {
      blocks.push(mealToBlock('afternoon', lunch, members));
    }
    if (afternoonActivity) {
      blocks.push(activityToBlock('afternoon', afternoonActivity, members));
    } else if (!lunch) {
      // Free afternoon if no activity and no lunch slot
      blocks.push({
        timeBlock: 'afternoon',
        type: 'free',
        title: 'Free time / explore',
        venue: 'Neighbourhood exploration',
        location: 'Local area',
        estimatedCostPerPersonUsd: 0,
        servesPreferences: {},
      });
    }

    // Evening: dinner
    const dinner = dayMeals.find(m => m.type === 'dinner');
    if (dinner) {
      blocks.push(mealToBlock('evening', dinner, members));
    }

    // Day cost = sum of block costs
    const dayTotal = blocks.reduce((s, b) => s + b.estimatedCostPerPersonUsd, 0);

    days.push({
      day,
      theme: buildDayTheme(blocks),
      blocks,
      dayTotalCostPerPersonUsd: Math.round(dayTotal * 100) / 100,
    });
  }

  return days;
}

function activityToBlock(
  timeBlock: TimeBlock,
  activity: ActivityCandidate,
  members: PlanningContext['members'],
): ScheduledBlock {
  const servesPreferences: Record<string, string[]> = {};
  for (const member of members) {
    const served: string[] = [];
    const all = [...member.priorities.mustHave, ...member.priorities.niceToHave];
    for (const pref of all) {
      if (preferenceMatchesCategory(pref, activity.category)) {
        served.push(pref);
      }
    }
    if (served.length > 0) servesPreferences[member.memberId] = served;
  }

  return {
    timeBlock,
    type: 'activity',
    title: activity.name,
    venue: activity.name,
    location: 'See activity description',
    estimatedCostPerPersonUsd: activity.estimatedCostPerPersonUsd,
    durationHours: activity.durationHours,
    travelTimeMinutes: 20,
    servesPreferences,
    notes: activity.accessibilityNotes,
  };
}

function mealToBlock(
  timeBlock: TimeBlock,
  meal: Meal,
  members: PlanningContext['members'],
): ScheduledBlock {
  const servesPreferences: Record<string, string[]> = {};
  for (const member of members) {
    const served: string[] = [];
    const all = [...member.priorities.mustHave, ...member.priorities.niceToHave];
    for (const pref of all) {
      if (preferenceMatchesMeal(pref, meal)) served.push(pref);
    }
    if (served.length > 0) servesPreferences[member.memberId] = served;
  }

  return {
    timeBlock,
    type: 'meal',
    title: `${capitalize(meal.type)} at ${meal.venue}`,
    venue: meal.venue,
    location: meal.cuisineType,
    estimatedCostPerPersonUsd: meal.estimatedCostPerPersonUsd,
    durationHours: 1,
    servesPreferences,
    notes: meal.notes,
  };
}

function preferenceMatchesCategory(pref: string, category: string): boolean {
  const map: Record<string, string[]> = {
    hiking:    ['hiking', 'outdoors'],
    nightlife: ['nightlife'],
    museums:   ['museums', 'culture'],
    beaches:   ['beaches'],
    adventure: ['adventure', 'sports'],
    mixed:     ['hiking', 'museums', 'culture', 'outdoors'],
  };
  const terms = map[category] ?? [];
  return terms.some(t => pref.toLowerCase().includes(t));
}

function preferenceMatchesMeal(pref: string, meal: Meal): boolean {
  const prefLower = pref.toLowerCase();
  if (prefLower.includes('street food') && meal.cuisineType.toLowerCase().includes('street')) return true;
  if (prefLower.includes('fine dining') && meal.venue.toLowerCase().includes('fine')) return true;
  if (prefLower.includes('local cuisine')) return true;
  return false;
}

function buildDayTheme(blocks: ScheduledBlock[]): string {
  const types = blocks.map(b => b.type);
  const activityBlocks = blocks.filter(b => b.type === 'activity');
  if (activityBlocks.length === 0) return 'Rest & Exploration Day';
  if (activityBlocks.length === 1) return `${activityBlocks[0]!.title} Day`;
  return `${activityBlocks[0]!.title} & ${activityBlocks[1]!.title} Day`;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Budget breakdown builder
// ---------------------------------------------------------------------------

function buildBudgetBreakdown(
  budget: BudgetProposal,
  ctx: PlanningContext,
): BudgetBreakdown {
  const lockedBudgetUsd = ctx.lockedBudget;
  const lines: BudgetLine[] = budget.lines.map(l => ({
    category: l.category,
    estimatedCostPerPersonUsd: l.estimatedCostPerPersonUsd,
    totalGroupUsd: l.totalUsd,
    pctOfBudget: lockedBudgetUsd > 0
      ? Math.round((l.totalUsd / lockedBudgetUsd) * 100)
      : 0,
  }));

  return {
    lines,
    totalPerPersonUsd: Math.round(budget.totalEstimatedUsd / ctx.groupSize),
    totalGroupUsd: budget.totalEstimatedUsd,
    lockedBudgetUsd,
    surplus: budget.surplus,
    notes: budget.overrunFlag
      ? `Over budget by $${Math.abs(budget.surplus).toFixed(0)}. Substitutions recommended: ${budget.substitutions.map(s => `${s.replace} → ${s.with} (saves $${s.savingUsd})`).join('; ')}`
      : `Within budget. Buffer: $${budget.surplus.toFixed(0)}.`,
  };
}

// ---------------------------------------------------------------------------
// Satisfaction scores builder
// ---------------------------------------------------------------------------

function buildSatisfactionScores(
  memberSatisfaction: MemberSatisfaction[],
  members: PlanningContext['members'],
  fairnessScore: number,
  fairnessFloorMet: boolean,
): SatisfactionScores {
  const perMember: PerMemberScore[] = memberSatisfaction.map(ms => {
    const snap = members.find(m => m.memberId === ms.memberId);
    return {
      memberId:          snap?.userId ?? ms.memberId,   // User.id for attributability
      memberRecordId:    ms.memberId,
      memberName:        ms.memberName,
      satisfactionPct:   ms.satisfactionPct,
      mustHaveFulfilled: ms.mustHaveFulfilled,
      niceToHaveFulfilled: ms.niceToHaveFulfilled,
      unmetMustHave:     ms.unmetMustHave,
    };
  });

  const groupSatisfactionPct = perMember.length > 0
    ? Math.round(perMember.reduce((s, m) => s + m.satisfactionPct, 0) / perMember.length)
    : 0;

  return { perMember, groupSatisfactionPct, fairnessScore, fairnessFloorMet };
}

// ---------------------------------------------------------------------------
// Tradeoff report — generated by Claude for human-readable narrative
// ---------------------------------------------------------------------------

async function generateTradeoffReport(
  ctx: PlanningContext,
  consensus: ConsensusResult,
  negotiation: NegotiationResult,
  budget: BudgetProposal,
  accommodation: AccommodationProposal,
): Promise<string> {
  const winner = consensus.winner ?? consensus.bestAvailable;
  if (!winner) return 'No itinerary was generated.';

  const memberLines = winner.memberSatisfaction
    .map(m => `  - ${m.memberName}: ${m.satisfactionPct}% satisfied (unmet must-haves: ${m.unmetMustHave.join(', ') || 'none'})`)
    .join('\n');

  const negotiationSummary = negotiation.rounds.length > 0
    ? `Negotiation ran for ${negotiation.rounds.length} round(s):\n` +
      negotiation.rounds.flatMap(r => r.resolutions).map(s => `  - ${s}`).join('\n')
    : 'No conflicts required negotiation.';

  const prompt = `You are TripSync's trip planning narrator. Write a plain-language tradeoff report for this group trip plan.

TRIP CONTEXT:
- Destination: ${ctx.destination}
- Duration: ${ctx.tripDuration} nights
- Group size: ${ctx.groupSize} people
- Locked budget: $${ctx.lockedBudget} total

CONSENSUS RESULT: ${consensus.status}
Total score: ${winner.totalScore}/100
Group satisfaction: ${winner.groupSatisfactionPct}%
Fairness floor met: ${winner.fairnessFloorMet ? 'YES' : 'NO (admin override may be needed)'}

Per-member satisfaction:
${memberLines}

Budget: $${budget.totalEstimatedUsd.toFixed(0)} estimated vs $${budget.lockedBudgetUsd.toFixed(0)} locked (${budget.overrunFlag ? 'OVER BUDGET' : `$${budget.surplus.toFixed(0)} buffer`})
Accommodation: ${accommodation.options[accommodation.recommended]?.name ?? 'TBD'}

${negotiationSummary}

Write a 3-5 paragraph plain-language tradeoff report covering:
1. What the plan gets right for the group as a whole
2. Key tradeoffs made (whose preferences were prioritised, what was left out and why)
3. Budget commentary and any overrun risks
4. If fairness floor was not met: which members got a worse deal and what the admin could do about it
5. One sentence congratulating the group and wishing them a great trip

Keep it warm, honest, and concise. Do not use headers. Write in second person ("your group").`;

  const response = await anthropic.messages.create({
    model: model(),
    max_tokens: 800,
    system: 'You are a friendly travel planner writing a clear, honest trip summary.',
    messages: [{ role: 'user', content: prompt }],
  });

  return response.content
    .filter(b => b.type === 'text')
    .map(b => (b as { type: 'text'; text: string }).text)
    .join('')
    .trim();
}

// ---------------------------------------------------------------------------
// Main assembler
// ---------------------------------------------------------------------------

export async function assembleItinerary(
  ctx: PlanningContext,
  activity: ActivityProposal,
  food: FoodProposal,
  accommodation: AccommodationProposal,
  transportation: TransportationProposal,
  budget: BudgetProposal,
  consensus: ConsensusResult,
  negotiation: NegotiationResult,
): Promise<FinalItinerary> {
  const winner = consensus.winner ?? consensus.bestAvailable;

  // Use the activities from the consensus winner; fall back to top-N from proposal
  const selectedActivities = winner
    ? winner.candidate.activities
    : activity.candidates.slice(0, Math.min(activity.candidates.length, ctx.tripDuration * 2));

  // Slot everything into day blocks
  const dayPlans = slotActivitiesAndMeals(
    selectedActivities,
    food.mealPlan,
    ctx.tripDuration,
    ctx.members,
  );

  // Budget breakdown
  const budgetBreakdown = buildBudgetBreakdown(budget, ctx);

  // Satisfaction scores (keyed to User via memberId)
  const memberSatisfaction = winner?.memberSatisfaction ?? [];
  const satisfactionScores = buildSatisfactionScores(
    memberSatisfaction,
    ctx.members,
    winner?.dimensions.fairness.raw ?? 0,
    winner?.fairnessFloorMet ?? false,
  );

  // Tradeoff report
  const tradeoffReport = await generateTradeoffReport(
    ctx,
    consensus,
    negotiation,
    budget,
    accommodation,
  );

  return {
    dayPlans,
    budgetBreakdown,
    satisfactionScores,
    tradeoffReport,
    adminOverrideFlag: consensus.adminOverrideFlag,
    negotiationRounds: negotiation.rounds.length,
    generatedAt: new Date().toISOString(),
  };
}

// Re-export for convenience
export type { ConsensusResult, NegotiationResult };
